### ISSUE TITLE
visualization from python

### ISSUE THREAD

**Issue by egavi** [jamesgregson/pyPolyCSG#1]
Very interesting project. Is exporting the OBJ the only way to visualize?
If not, is it something you could add? thanks

**Comment by jamesgregson** [comment]
I've updated the repo so that the wrapper provides mesh level access.  From python you can now used:

obj.num_vertices() - returns number of polyhedron vertices
obj.num_faces() - returns number of polyhedron faces
obj.num_face_vertices() - returns the number of vertices for a given face
obj.get_vertex( id ) - return the coordinates of the id'th vertex (as a tuple)
obj.get_face( id ) - returns the vertex indices for the id'th face (as a list)

In addition, if you'd just like to get everything at once, e.g. to use with glDrawElements, you can use
obj.get_vertices() - returns vertex coordinates as a 2D numpy array
obj.get_triangles() - temporarily triangulates the mesh and returns a 2D numpy array of triangle vertex ids

So this should allow visualization via opengl (or whatever you like) in python natively, without exporting the mesh.

James
