### ISSUE TITLE
normals for triangles

### ISSUE THREAD

**Issue by egavi** [jamesgregson/pyPolyCSG#2]
Hello,
thank you for having added the possibility to get meshes / triangles.
- can you please explain how to get the normals? I mean, to understand which side of the triangle faces outside (air) and which one faces the interior of the object (solid).
  thanks!

**Comment by jamesgregson** [comment]
Hi,

The normals are outward facing, i.e. point from the interior of the polyhedron to the 'air', as is pretty standard in graphics.

If you've called get_triangles() and have the vertices for a single triangle stored as tuples p0, p1 and p2 then the normal will be:

N = (p1-p0) X (p2-p0)

where X is the vector cross-product.  The length of N will then be twice the area of triangle, so before drawing in opengl, you should normalize it.

Using the notation above, python code to compute the normal for that triangle is:

u = ( p1[0] - p0[0], p1[1] - p0[1], p1[2]-p0[2] )    # compute first offset vector u = p1-p0
v = ( p2[0] - p0[0], p2[1] - p0[1], p2[2]-p0[2] )    # compute second offset vector v = p2-p0
N = ( u[1]_v[2]-u[2]_v[1], u[2]_v[0]-u[0]_v[2], u[0]_v[1]-u[1]_v[0] )  # compute N = u X v
L = max( 1e-10, math.sqrt( N[0]_N[0] + N[1]_N[1] + N[2]*N[2] ) )  # compute length of N, clamp to 1e-10
N = ( N[0]/L, N[1]/L, N[2]/L ) # normalize N, clamping above prevents divide by zero, N now holds the triangle normal

If you want 'smooth' shading, then you have to subsequently average the triangle normals to the vertices. There are many ways to do this, all with pros and cons, but it's kind of outside the scope of this code.

Hope this helps,

James

**Comment by dbc** [comment]
This is the best way I've found so far for generating face normals:

```
        v = polyBlock.get_vertices()
        t = polyBlock.get_triangles()
        n = numpy.array([numpy.cross(v[t[i][1]]-v[t[i][0]], \
                            v[t[i][2]]-v[t[i][0]]) for i in xrange(len(t))])
        for i in xrange(len(n)):
            vv = n[i]
            n[i] = vv/(numpy.sqrt((vv**2).sum()))
```

The resulting numpy array 'n' is an array of face normals usable for flat shading.

numpy and generator expressions don't seem to get along so well.  Otherwise I'd create a generator expression for the cross-product results and realize the list of normalized face normals.  The above code realizes a list of cross products, and then goes into a loop to normalize each one.  A little less elegant, but at least it avoids creating a giant temporary numpy array, which might get painful in the cases where there are lots of vertices.

I haven't benchmarked this, so there are no doubt improvements to be found.
